/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hotelmanagementsystem;

import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author user
 */
public class CustomerRecord extends javax.swing.JPanel {

    /**
     * Creates new form Reports
     */
    
    DefaultTableModel dtm;
    
    
    
    public void showData(){
        try{
            PreparedStatement pst =  DBConnection.db.get().prepareStatement("select customers.customer_id,customers.id_num,customers.name,customers.phone,customers.room_number,customers.ck_time,bill_info.ckout_time,bill_info.std,bill_info.bill from customers inner join bill_info on customers.customer_id = bill_info.id_num  where living_status = ? order by ckout_time desc ");
            pst.setString(1, "Out");
           ResultSet rs = pst.executeQuery();
            while(rs.next()){
                Object[] data = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)};
                dtm.addRow(data);
            }
        }catch(Exception a){
            System.out.println(a);
        }
         
        
    }
    
    
    public CustomerRecord() {
        initComponents();
        
        dtm= new DefaultTableModel(new String []{"Customer Id","Photo Id Number","Name","Phone","Room Number","Checkin Time","Checkout Time","Staying Days","Bill"},0);
        jTable1.setModel(dtm);
        jTable1.setShowGrid(true);
        
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        sid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        snum = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Record List");

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Search By ID :");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setShowGrid(false);
        jScrollPane1.setViewportView(jTable1);

        sid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sidKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel3.setText("Search By PhoneNumber :");

        snum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snumActionPerformed(evt);
            }
        });
        snum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                snumKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(492, 492, 492)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(snum, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(snum, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sidKeyReleased
        // TODO add your handling code here:
    
         try{
            PreparedStatement pst =  DBConnection.db.get().prepareStatement("select customers.customer_id,customers.id_num,customers.name,customers.phone,customers.room_number,customers.ck_time,bill_info.ckout_time,bill_info.std,bill_info.bill from customers inner join bill_info on customers.customer_id = bill_info.id_num where living_status = ? and customers.id_num = ?");
            pst.setString(1, "Out");
            pst.setString(2, sid.getText());
            dtm.setRowCount(0);
           ResultSet rs = pst.executeQuery();
            if(rs.next()){
                Object[] data = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)};
                dtm.addRow(data);
            }else{
                showData();
            }
        }catch(Exception a){
            System.out.println(a);
        }
        
    }//GEN-LAST:event_sidKeyReleased

    private void snumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_snumActionPerformed

    private void snumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snumKeyReleased
        // TODO add your handling code here:
        try{
            PreparedStatement pst =  DBConnection.db.get().prepareStatement("select customers.customer_id,customers.id_num,customers.name,customers.phone,customers.room_number,customers.ck_time,bill_info.ckout_time,bill_info.std,bill_info.bill from customers inner join bill_info on customers.customer_id = bill_info.id_num where living_status = ? and phone = ?");
            pst.setString(1, "Out");
            pst.setString(2, snum.getText());
           
            dtm.setRowCount(0);
           ResultSet rs = pst.executeQuery();
            if(rs.next()){
                Object[] data = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)};
                dtm.addRow(data);
            }else{
                showData();
            }
        }catch(Exception a){
            System.out.println(a);
        }
        
    }//GEN-LAST:event_snumKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField sid;
    private javax.swing.JTextField snum;
    // End of variables declaration//GEN-END:variables
}
